{% set name = "semvecpy" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f326116e267d3a673dff576483b5fba3f36ca878da688ef10a864ed4504f390c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >3.5
    - bitarray
    - numpy
  run:
    - python >3.5
    - bitarray
    - numpy

test:
  imports:
    - semvecpy
    - semvecpy.permutations
    - semvecpy.vectors

about:
  home: https://github.com/semanticvector/semvecpy
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Semantic Vectors work in Python

extra:
  recipe-maintainers:
    - hannahburkhardt
    - jusger
