{% set name = "semvecpy" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e61229e6268719cacd5178a8cf2fee42eb261fd11f8aff6a57b718417c11b2f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >3.5
    - bitarray
    - numpy
  run:
    - python >3.5
    - bitarray
    - numpy

test:
  imports:
    - semvecpy
    - semvecpy.permutations
    - semvecpy.vectors

about:
  home: https://github.com/semanticvector/semvecpy
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Semantic Vectors work in Python

extra:
  recipe-maintainers:
    - hannahburkhardt
    - jusger
