travis:
  secure:
    BINSTAR_TOKEN: MijScvGeTxliz8wJNGDniChk+ckwQRFAizl5p6o54xucYFJngt3g7POBMvujt6N/x/9hZvJ0cdXnwzAtEuG1h7qe7qDj1CoCz/0Y6Qvz5KeVddTgaO8enlOgj7GPkyp2xoEgubhFA/H9zT3t/YmG6t4OjRhy1+HqpAwnR3+xKQj+0cev1ZaBcTs1Kt1paV4Ri3dp9ymq9R3gljzvtN0pFc1ZePH0jXttTAJ8Xjl6gzTQ1LplK0tYdrWwYUPSR3zLZkLvZLA2wdQ32RwKvrIwdZDfxmiPmjiAVALZRChznFolx20mmdCuhOPy6pGVitm4l/cb9PBZQzpQ/BAqqtm7b0hxx5hzCD/YFDtYJkWU22frXM2vohWiX0bKWHWWgzhqee3uaSO9ZbyYBY2u6NgftX1fQzKW5rNL5641enoFWppyVUyruKCJu1Yb1b3OOWdSnry1qI4a9dHDpbvHp0W1iXh49l7YhZQc8cp/tuUS1OPr3IEwroCcoxNEg0kiJuPPz0Avgh9meLaYlRfTO66aLu2lxIO+JfzE4uOToV1MkdIXShe9RPY3HHUe5IPl2R0bg7KPzZz4QlXaR4AkfAOZR9onfZW49A2/Bu1A3dCtSK5kyD10013VB4sQGzDaRx75Gf2XwGk8/QWzwyxr+Drif0hobl6dRuoZPSDnlPGejZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
