travis:
  secure:
    BINSTAR_TOKEN: Gi/3IfmXB4SGg4SUB1Pn1breCkzRIZ9A0ODGxr8jEM2LcSdsLCxa0XwDJo9U/jtghwiNFleGDeQByFl/CNeMBPBYsZnCSn41vWLV5qqvJj+TxDuK0Ak72dYs06j2cNRvyT22AQR996I15s6/9K1KC8PDvffBEvg/vEBU7bPhmas84MpryJmNhn+q06COgkBt8HnXcgY+uH9UYdG4vL/lNbkgAGasplzNM9IjodaHoOrUbjrUsJEPOrZwKwnLbcenqf0YzPVKfk6ceGIz7Ico+qKzGKlwD7Yq9AcOoMyCL9lH+Z/Vt+Q0wLmR3QUkalRCTRK7YKhjP/qSDemh6BynPVfr7SFCEKP8QUitWDke1T37GGIJCDyJXA4oTU5+JiFntVqljwoCowRJojFWXFGXLqBU1OxHZcDdTTA6bXYf8K7HiM8e7kdl4nQ5JZ6vpYzIefnNLvGzw43AZ6vMS2sijVDi4A88lMN1NXjV6DUJIFs60fidDLRAZg8lqMkj88x9L7WbrLOsUJpK1vp01KLc/emtUT5pVJjiAy+wsW3uB2ZLLV3Yxze/pW+xdtaluPZYsVIdPy6lH2UtVQs89YFbRDufxP7Aa2TVUSnUGq7oTdE8mwqxye/ZK9h5C3vBSeOTBhLTbLuQkeqEN79/pgD0QdNKRHBcJxMrepyB+zMWS+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
